name: 'Action name'
description: 'Action description'
author: 'italia'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  repo:
    description: 'GitHub repository italia/publiccode-parser-action'
    default: ''
    required: true

outputs:
  stars:
    description: 'The stars of the repository'
  license:
    description: 'The license used in the repository'

runs:
  using: 'bash'
  main: 'github-downloader.sh'
  post: 'github-downloader.sh'

branding:
  icon: 'activity'
  color: 'white'
