name: 'Action name'
description: 'Action description'
author: 'italia'

inputs:
  filepath:
    description: 'File Path To Place Files'
    default: ''
    required: false
  repo:
    description: 'GitHub repository italia/publiccode-parser-action'
    default: ''
    required: true
  overwrite:
    description: 'Overwrite Files In Repo'
    default: ''
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.filepath }}
    - ${{ inputs.OverwriteFile }}

branding:
  icon: 'activity'
  color: 'white'
