#!/bin/bash

#####################################################
#  Download Specific folders from Github using SVN
#  
#  Orginal Author: Declan Cook
#  Modified by: MarketingPip from github.com/MarketingPipeline
#  Licence: MIT
#####################################################
GHDOMAIN="https://github.com/"
IN=$1
FILEPATH=$2
IN=${IN##$GHDOMAIN}
BRANCH="trunk"
FOLDER=""
IFS="/" read -a SECT <<< "$IN" 

if [ -z "$FILEPATH" ]
then
      echo "\FILEPATH is empty"
      FILEPATH="./"
else
      echo "\FILEPATH is NOT empty"
      FILEPATH=$FILEPATH
fi

if [[ "${SECT[3]}" != "master" ]]; then
  BRANCH=${SECT[3]}
fi
for index in "${!SECT[@]}"; do
  if [ $index -gt 3 ]; then
    FOLDER=$FOLDER/${SECT[index]}
  fi
done

# DOMAIN/USER/PROJECT/<TRUNK||BRANCH>/FOLDER
echo Exporting $GHDOMAIN${SECT[0]}/${SECT[1]}/$BRANCH$FOLDER
svn --force export $GHDOMAIN${SECT[0]}/${SECT[1]}/$BRANCH$FOLDER $FILEPATH
