name: GitHub Downloader
# Define when to run job here
on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Runing Github Downloader
    steps:
    - uses: actions/checkout@v2
    - uses: MarketingPipeline/GitHub-Downloader-Action@main
      with:
        # Define the folder or file to download
        repo: https://github.com/MarketingPipeline/Awesome-Repo-Template/blob/master/.github/py_repo_tools/replace_repo_links.py

     # Commit the updates
    - name: Commit and Push Downloaded Files 
      run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Added Downloaded File"
         git push
